### ISSUE TITLE
Inconsistency in the name of the GitHub repos

### ISSUE THREAD

**Issue by akane6704** [Vacaro/Vacaro#6]
The games for the GitHub repos now it's just a mess.
There are repos James AvdanOS, grub-theme, Tina, like seriously what's going on?
I suggest to name the repos like `cool-repo` or `Cool-Repo`, or maybe `CoolRepo`, that we'll use for all the repos.

**Comment by froxcey** [comment]
Since the name of the organisation has a dash, so maybe it's a good idea to name repos with dashes.

**Comment by AZProductions** [comment]
> Since the name of the organisation has a dash, so maybe it's a good idea to name repos with dashes.

I agree

**Comment by akane6704** [comment]
So we're going to name all the repos `example-repo`?

**Comment by akane6704** [comment]
Btw sorry for mispronouncies in the issue that i wrote but i'm writing it from my phone, and i don't disabled auto-corrector

**Comment by AZProductions** [comment]
`Example-Repo` is the option we're going for

**Comment by akane6704** [comment]
Ok thx

**Comment by akane6704** [comment]
I'll close the issue when all the repos will be renamed correctly
