### ISSUE TITLE
Suggestion: Documentation

### ISSUE THREAD

**Issue by TeggolT** [Vacaro/Vacaro#7]
Hello, I think this project is missing any Documentation. Documentation is very important when creating a project like an OS/a distro that is meant to be used seriously. However, many FOSS projects, including this one, haven't got a solid or even basic documentation.

I suggest to change that by creating a new repository (avdanos/doc or something) and letting people contribute.

There are two main ways I think you could do that:

1.Use Wikimedia to create a good documentation without having to worry about the code

2.Code a custom doc site including the avdanos design language

You could start with option 1 and then switch to option 2 when you have the time to do so. Also, you could wrap it into a "help" or "tipps" app.

The documentation would also be a good answer to "i don't know how to code, can i contribute anyway?".

**Comment by froxcey** [comment]
Remember, this is all subject to change

The current plan is to have two parts of documentation, dev doc and user manual. The lower level information about this project, including how to contribute, should be in a section of the AvdanOS dev doc. How the doc will be made is still being discussed, but the possibility of a docs repo is highly likely, almost certain.
